=== dealexce/FactoRL-Assets/FactorProjects/MRP3D/Scenes/CMSv3/config/description-model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="scenario" type="Scenario"/>
    <xs:complexType name="Scenario">
        <xs:all>
            <xs:element name="model" type="Model"/>
            <xs:element name="layout" type="Layout"/>
        </xs:all>
    </xs:complexType>
<!--    Model    -->
    <xs:complexType name="Model">
        <xs:all>
            <xs:element name="modelName" type="xs:string"/>
            <xs:element name="itemStates" type="ItemStates"/>
            <xs:element name="processes" type="Processes"/>
            <xs:element name="workstations" type="Workstations"/>
            <xs:element name="agv" type="Agv"/>
        </xs:all>
    </xs:complexType>
    <!--    Item State    -->
    <xs:complexType name="ItemStates">
        <xs:sequence>
            <xs:element name="itemState" type="ItemState" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ItemState">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="idref" type="xs:IDREF"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    
    <!--    Process    -->
    <xs:complexType name="Processes">
        <xs:sequence>
            <xs:element name="process" type="Process" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Process">
        <xs:sequence minOccurs="0">
            <xs:element name="inputs" type="Inputs" minOccurs="1"/>
            <xs:element name="outputs" type="Outputs" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="duration" type="xs:float"/>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="idref" type="xs:IDREF"/>
    </xs:complexType>
    <xs:complexType name="Inputs">
        <xs:sequence>
            <xs:element name="inputItemState" type="ItemState" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Outputs">
        <xs:sequence>
            <xs:element name="outputItemState" type="ItemState" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--    Workstation    -->
    <xs:complexType name="Workstations">
        <xs:sequence>
            <xs:element name="workstation" type="Workstation" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Workstation">
        <xs:all minOccurs="0">
            <xs:element name="supportProcesses" type="SupportProcesses" minOccurs="1"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="idref" type="xs:IDREF"/>
    </xs:complexType>
    <xs:complexType name="SupportProcesses">
        <xs:sequence>
            <xs:element name="supportProcess" type="Process" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--    Agv    -->
    <xs:complexType name="Agv">
        <xs:attribute name="move-speed" type="xs:float" use="required"/>
        <xs:attribute name="rotate-speed" type="xs:float" use="required"/>
        <xs:attribute name="capacity" type="xs:integer" default="1"/>
    </xs:complexType>
    
    
<!--    Layout    -->
    <xs:complexType name="Layout">
        <xs:all>
            <xs:element name="groundSize" type="GroundSize"/>
            <xs:element name="workstationInstances" type="WorkstationInstances"/>
            <xs:element name="agvInstances" type="AgvInstances"/>
            <xs:element name="importStation" type="ImportStation"/>
            <xs:element name="exportStation" type="ExportStation"/>
        </xs:all>
    </xs:complexType>
    <xs:attributeGroup name="Position">
        <xs:attribute name="x" type="xs:float" default="0"/>
        <xs:attribute name="y" type="xs:float" default="0"/>
    </xs:attributeGroup>

    <xs:complexType name="GroundSize">
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
    </xs:complexType>
    <xs:complexType name="WorkstationInstances">
        <xs:sequence>
            <xs:element name="workstationInstance" type="WorkstationInstance" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="WorkstationInstance">
        <xs:all>
            <xs:element name="workstationModel" type="Workstation"/>
        </xs:all>
        <xs:attributeGroup ref="Position"/>
    </xs:complexType>
    <xs:complexType name="AgvInstances">
        <xs:sequence>
            <xs:element name="agv" type="AgvInstance" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AgvInstance">
        <xs:attributeGroup ref="Position"/>
    </xs:complexType>
    <xs:complexType name="ImportStation">
        <xs:attributeGroup ref="Position"/>
    </xs:complexType>
    <xs:complexType name="ExportStation">
        <xs:attributeGroup ref="Position"/>
    </xs:complexType>
</xs:schema>

=== dealexce/FactoRL-Assets/FactorProjects/MRP3D/Scenes/CMSv3/config/Scenario01-init.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="description-model.xsd">
    <model>
        <modelName>Scenario01</modelName>
        <itemStates>
            <itemState id="AR" name="A-Raw"/>
            <itemState id="A1" name="A-1"/>
            <itemState id="AP" name="A-Product"/>
            <itemState id="BR" name="B-Raw"/>
            <itemState id="B1" name="B-1"/>
            <itemState id="BP" name="B-Product"/>
            <itemState id="CR1" name="C-Raw1"/>
            <itemState id="C1" name="C-1"/>
            <itemState id="CR2" name="C-Raw2"/>
            <itemState id="CP" name="C-Product"/>
            <itemState id="S1" name="ScrewT1"/>
            <itemState id="S2" name="ScrewT2"/>
            <itemState id="G" name="Glue"/>
        </itemStates>
        <processes>
            <process id="PA1">
                <inputs>
                    <inputItemState idref="AR"/>
                    <inputItemState idref="S1"/>
                    <inputItemState idref="G"/>
                </inputs>
                <outputs>
                    <outputItemState idref="A1"/>
                </outputs>
            </process>
            <process id="PA2">
                <inputs>
                    <inputItemState idref="A1"/>
                    <inputItemState idref="S2"/>
                </inputs>
                <outputs>
                    <outputItemState idref="AP"/>
                </outputs>
            </process>
            <process id="PB1">
                <inputs>
                    <inputItemState idref="BR"/>
                    <inputItemState idref="S1"/>
                </inputs>
                <outputs>
                    <outputItemState idref="B1"/>
                </outputs>
            </process>
            <process id="PB2">
                <inputs>
                    <inputItemState idref="B1"/>
                    <inputItemState idref="S2"/>
                </inputs>
                <outputs>
                    <outputItemState idref="BP"/>
                </outputs>
            </process>
            <process id="PC1">
                <inputs>
                    <inputItemState idref="CR1"/>
                    <inputItemState idref="S1"/>
                </inputs>
                <outputs>
                    <outputItemState idref="C1"/>
                </outputs>
            </process>
            <process id="PC2">
                <inputs>
                    <inputItemState idref="C1"/>
                    <inputItemState idref="G"/>
                </inputs>
                <outputs>
                    <outputItemState idref="CP"/>
                </outputs>
            </process>
        </processes>
        <workstations>
            <workstation name="A-1 Assembler" id="W1">
                <supportProcesses>
                    <supportProcess idref="PA1"/>
                </supportProcesses>
            </workstation>
            <workstation name="ScrewT1 Adder" id="W2">
                <supportProcesses>
                    <supportProcess idref="PB1"/>
                    <supportProcess idref="PC1"/>
                </supportProcesses>
            </workstation>
            <workstation name="ScrewT2 Adder" id="W3">
                <supportProcesses>
                    <supportProcess idref="PA2"/>
                    <supportProcess idref="PB2"/>
                </supportProcesses>
            </workstation>
            <workstation name="C-Product Assembler" id="W4">
                <supportProcesses>
                    <supportProcess idref="PC2"/>
                </supportProcesses>
            </workstation>
        </workstations>
        <agv move-speed="5" rotate-speed="5" capacity="1"/>
    </model>
    <layout>
        <groundSize x="50" y="50"/>
        <workstationInstances>
            <workstationInstance x="0" y="0">
                <workstationModel idref="W1"/>
            </workstationInstance>
            <workstationInstance x="0" y="0">
                <workstationModel idref="W2"/>
            </workstationInstance>
            <workstationInstance x="0" y="0">
                <workstationModel idref="W3"/>
            </workstationInstance>
            <workstationInstance x="0" y="0">
                <workstationModel idref="W4"/>
            </workstationInstance>
        </workstationInstances>
        <agvInstances>
            <agv/>
        </agvInstances>
        <importStation/>
        <exportStation/>
    </layout>
</scenario>
